### ISSUE TITLE
スコアの表示

### ISSUE THREAD

**Issue by ChoeHwi** [ChoeHwi/Rtrain#9]
ゲームシーンにUIを作って
電車が通り過ぎた数を表示。
現在の運賃を計算する。
乗ってから経過した駅数×一駅当たりの運賃を一人ごとに求めて合計を表示

**Comment by Snow-Castle** [comment]
UIテキストで「Score」プレハブを作成しました。
「Score」にはScript「UI_Score」がついています。
「UI_Score」はリセット用の「Restart()」関数と、スコア（運賃）を加算する「ScoreUpdate(int fare)」関数が存在します。
int fare は加算する運賃を渡してください。
